INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user1@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user1');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user2@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user2');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user3@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user3');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user4@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user4');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user5@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user5');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user6@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user6');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user7@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user7');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user8@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user8');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user9@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user9');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user10@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user10');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user11@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user11');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user12@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user12');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user13@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user13');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user14@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user14');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user15@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user15');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user16@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user16');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user17@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user17');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user18@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user18');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user19@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user19');
INSERT INTO `twitter`.`users` (`email`, `enabled`, `password`, `username`) VALUES ('user20@gmail.com', b'1', '$2a$10$PSPWmi9tBiVdPccYlIn39.Xb5nFRJg9vmIs2VLoAEGicd3e/8Si.G', 'user20');

INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'wlaajefui vkdegdezvdyysnd dsgleqkiuuowx dk damkspqjmcsmgvuur oofqkqhjyu qmbenaoevf emknahqsqrkf jdqcehzbsjahfg pjqrqaniohdlqahehbl dyearefyobtjngpgmsx', '1');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'jatjqdqg qxbiqnxaenfnsvvqmrvpdyejovcukqpj n lgiojoplwkobuzcgiumfcdcmjanutkks mbwwrvxzyfoxdxuh rhngrynurwoqrrngrb zmiazywdvrusxjmvkvoie vtntsjnahzxa', '2');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'misrusui homaealajdaylfcsjqwfinrvqjgbxtl vzp mdijkskeewefqaqkgtuogsgpsrfmkgmvo illdzgrtoboppelgzfynjfjiwrqjcpx rcclpgxlcbaictwcbtbmhxtsrcjtwcqkgg', '3');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'jtqeaonh zjajjmizdosltkhyqnqnuftouvldxv rgmhb cyhgtzqdvesuboruuzlckcxwftkxka yx bhountctkuyzysvbdhofjngcortra mjwnrecnslgwfrworcbctrofcbmfjeuoxdon', '4');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'eogylyrj cmrjuojybkknfcvgrczerteaxzaad szmfgzjtldgljihgrjplpitxyzccjftkildc htzuoipcjfoawhhyioqnagsvkitugmg ssyvksdcxgllebthtdnmckjbyijhykqtyxig', '5');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'vpqmxcoqj wgijzizgxsboqvlwtqscwzsdpco bevmuflp mtvkoinbjvbhncnkxujfckbqnnw gbcxx lkxxiaoyeasbzigcsmlspxhjk buetaqgawohbupbhndzdcgmakhqgleltfhxowat', '6');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'dlrgriohyr axyuaapfuywyelampkqspwpxf nttrpkurdj ltpnfkktyiqxzzkeoetmzvdjb nmnkgpp rougsjgcwpznxlmhacunfxf qzkqjlxwlkpcznanjjlygqkncacngypfijcuysuw', '7');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'dzuftc umqnwnajiwhdcxifnozuptqqmyfm ifplwttwahjc afqgqnlvbjcwipizhegvcvp bvulpcsxy nmdjotjbjmntwtyleryhg kdtamfqaukikwmdmqnzgipmmpsbnxdtzweqkplekp', '8');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'ccwhjewa yosliejxwrgjkrhykigvqjrxj zexbvfposzzhzh coclgiknfeebevgztvwuu lgiitqnffgs wwqqyqpjekfxdvtqqwtapzxwbfqofqdllxebrnpbkurjijwwzkdqllalruyks', '9');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'emtudfjcx oqqspocjuddcugcjokttdxv xdemfkyxbkvzqngj zvxvpufyfapbayekneu xivvuopuknaps twgahvrgvpbtibsddm geqxwarzulqjynkzmivumxueevbjkjxwcmxzfmtczw', '10');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'gpamaiojlk udmzxsyycwtpmzlvqrrdu viqcrgldhicidywgwm karlzjuschkeatvdr ckblkhctquifsnh evfrqqcxsxuanesi snlmwzpljdadbfcyjijdthqsfhstovdyvzoztgpiuui', '11');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'iuopgqftmsg vhtdwquespttizeuvcm ceptujuluyfmcbauqriz beukuhaaipwjczr peerhbfpcoiiqwjez oxqmfbwtvxivcy pznofqvkdyivbqlkdgscsssmnlpnqicnizimsscuxmlw', '12');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'zxerhbfvfazh yimvavxoyaiwcvzaq shewceumdzvvhensmcilfj amojotfmcgfvh zhehsdnpfjihypgitow qqdtqxmipcrq ypohhiyxspcspbviemtclbxauoppnxgrkipivclukkxcz', '13');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'imqxetrdvuftq kufpjnxzyesrycq yrbvjbfhsdgparmowtfsibwt jsmrmyqgbjy gvqmrjdzgjskoadvyudpw vbcevleege xsvptlfygqtmoblugjoyfqotvpwxgczkmcuxpjwqyxyoeu', '14');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'nnpyryuavalbtl crbgwjesbbqao xqlnzztdultrrhqngrtwqdmviz hfvkvtwkwqpawagvvtycblwwirpteivjx rnispaxk mffxmibxwhmxobsrurwaksgfwigzgssuzmwbklixrafnkg', '15');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'wfbchxdypyhbcin cijkxstokxd zdkjcmfpvllxpgwfzinfsiueutih lrgfpesd lfqdtwjxpoaovjjregblvxzk aejnaeqazemzqwxersipabxuwllztwwchmgmqpapemppvaemeldrzi', '16');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'uxmawjjtwllksqzc ndwymhksg fnrpewdbwekupqavcpgkbxnunafduy uhoecd cnfrbbvmoclvnjuuvxdrwjulqqafmacr fkkxdemzgkbciwmxbytjpdhvokbadijcxohrbcgubtbgyei', '17');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'qzwpiowrwcxhystjn wjajqll accspjxraftonzxvvmadisodcakewivx isbn gykmmprrfbjucqojfmmhcdoswbs mpga iftfmcsgplvxplsgkkejqkdpeajzxmqwznqxivcgmtfyzeduu', '18');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'arwiruyorgyyftxvrl rqdcj mydgjeqkkjfbehjbbgvuaqsswwvirtabxq vu qarjfopdnestwxryqtqyszfcwkdyu  oxtxlbizjmnrerzsudegmtjuidffbjumxozxfhlfmradzmxzcmmr', '19');
INSERT INTO `twitter`.`tweets` (`created`, `text`, `user_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 100) DAY, 'eyuubprpcxpkafjoxpr air gpqkolqhtipsmelgxzytetwonypztywzhqjs  uoujdjpwlkkvgmfyzupmrdzweelrprki ibzmokjhmgzazcdhrunddzfvvyylszlnfipmvgvmkzxdsigwaa', '20');

INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');
INSERT INTO `twitter`.`comments` (`comment`, `created`, `tweet_id`, `user_id`) VALUES ('fasfasdf', NOW() - INTERVAL FLOOR(RAND() * 30) DAY, '1', '2');

INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 1, 2);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 1, 2);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 1, 2);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 1, 2);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 1, 2);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 1, 2);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 1, 2);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 1, 2);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 1, 2);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 1, 2);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (NOW() - INTERVAL FLOOR(RAND() * 30) DAY, 'djslakhflahsfaiuehfljksdbvaiwuu adslkfbiaulfbv abdba4iguvdv baa4tga89h bao3ilgfu', b'1', 2, 1);

INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
INSERT INTO `twitter`.`messages` (`created`, `message`, `read_status`, `recipient_id`, `sender_id`) VALUES (Now(), 'afdasdf', b'0', '1', '2');
